### Export path for importing class from custom package defined

In [1]:
#PYTHONPATH=$PYTHONPATH:/Laxman/Project/Python/logisticReg
#export PYTHONPATH
import sys
sys.path.append("/Laxman/Project/Python/logisticReg")

### Importing necessary libraries

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix,roc_curve, auc, accuracy_score
import numpy as np
#from lib.libraryfile import custom_estimator, ThresholdBinarizer
from pkgCustom.custom_estimator import custom_estimator
from pkgCustom.ThresholdBinarizer import ThresholdBinarizer

### Imported Iris data set from sklearn library
#### And, converted all the target values greater than 1 to 1. It will make all the targets 0 or 1. 
#### It will become binary classification problem

In [3]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
# to make the problem as binary classification converted greater than 1 to 1 
y=np.where(y>1, 1, y)

In [5]:
#splitting the dataset in 80/20 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

##### Below code is just to suppress the warning received at the time of initializing logistic regression model

In [6]:
# import warnings filter
# to reduce the warning received while initializing model
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [7]:
#Calling the class constructor to initialize the training dependent and independent features
modelLogisticRegression = custom_estimator(X_train, y_train)

In [8]:
# Training the model using train dataset 
modelLogisticRegression.fit()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
# Gettting the predictions based on the test data i.e, 20% of whole data
predictions = modelLogisticRegression.predict(X_test)

In [10]:
# initializing the threshold binarizer using test dataset and test target
metricEvaluation = ThresholdBinarizer(X_test, y_test)

In [11]:
# Collecting prediction probability from the test data
predictions =modelLogisticRegression.predict_prob(X_test)

#### Applied threshold from 0 to .99 with the interval of .05

In [12]:
threshold = [0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,.7,.75,.8,.85,.9,.95,.99]
finalValue = []
for indThsld in threshold:
    #y_pred = np.where(predictions[:,1]>indThsld,1,0)
    thsld_pred = metricEvaluation.accuracy(predictions,indThsld)
    print(thsld_pred)
    finalValue.append(metricEvaluation.Gini(thsld_pred))

[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0]
[1 0 1 1

In [13]:
# printing the final output. It looks .95 is the threshold with max Gini impurity.
finalValue

[0.7600000000000001,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9800000000000001,
 0.82]

In [14]:
!pip freeze > requirements.txt